sudo: true

addons:
    apt:
        sources:
        - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
        - ubuntu-toolchain-r-test # gcc-4.8 / g++-4.8
        packages:
        - cmake
        - cmake-data
        - g++
        - gcc-4.8
        - g++-4.8
        - pkg-config
        - ragel
        - libbz2-dev
        - libpcap-dev
        - tree

language: go

go:
    - 1.7.x
    - 1.8.x
    - 1.9.x
    - master

install:
    - go get -v github.com/hashicorp/go-multierror
    - go get -v github.com/google/gopacket
    - go get -v github.com/smartystreets/goconvey/convey

before_install:
    - .travis/setup-travis.sh

before_script:
    - .travis/build-hyperscan.sh

script:
    - go test ./...

env:
    global:
        - BOOST_VERSION_MINOR=63
        - BOOST_ROOT=$HOME/boost-1.$BOOST_VERSION_MINOR
        - HYPERSCAN_VERSION=4.5.2
        - HYPERSCAN_ROOT=$HOME/hyperscan-$HYPERSCAN_VERSION
        - PKG_CONFIG_PATH=$HYPERSCAN_ROOT/lib/pkgconfig:$BOOST_ROOT/lib/pkgconfig
        - DYLD_LIBRARY_PATH=$HYPERSCAN_ROOT/lib:$BOOST_ROOT/lib

after_failure:
    - echo `pwd`
    - tree -h

cache:
    directories:
    - $BOOST_ROOT
    - $HYPERSCAN_ROOT
